### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by ppacher** [ppacher/homebot#2]
# Task Summary for better documentation

- [ ] Readme
  - [ ] Add build/local setup instructions
  - [ ] Add a more detailed description about the project
- [ ] General Documentation
  - [ ] Describe the overall concept (i.e. devices, sensors, commands, ...)
  - [ ] Describe the Dependency Injection
  - [ ] Documenation for the MQTT protocol (i.e. exchanged messages/topics)
